# Generated by Django 4.0.2 on 2022-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2004-05-07'),
            preserve_default=False,
        ),
    ]
